import ClientHeader from '@/components/ClientHeader';

export const metadata = {
	title: 'Client Template',
	description: 'Generated by create next app',
};

export default function ClientLayout({ children }: Readonly<{
	children: React.ReactNode;
  }>) {
	return (
		<main className={`antialiased flex flex-col bg-slate-200`}>
			<ClientHeader />
			<div className='flex-1 flex-center'>{children}</div>
		</main>
	);
}
