import PublicHeader from '@/components/PublicHeader';

export const metadata = {
	title: 'Client Template',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<main className={`antialiased flex flex-col bg-blue-100`}>
			<PublicHeader />
			<div className='flex-1 flex-center'>{children}</div>
		</main>
	);
}
